# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DatasetPanel.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DatasetPanel(object):
    def setupUi(self, DatasetPanel):
        DatasetPanel.setObjectName("DatasetPanel")
        DatasetPanel.resize(258, 445)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(DatasetPanel)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(DatasetPanel)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.colorByCombo = QtWidgets.QComboBox(DatasetPanel)
        self.colorByCombo.setObjectName("colorByCombo")
        self.horizontalLayout.addWidget(self.colorByCombo)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.legendListWidget = QtWidgets.QListWidget(DatasetPanel)
        self.legendListWidget.setObjectName("legendListWidget")
        self.verticalLayout_3.addWidget(self.legendListWidget)
        self.groupBox = QtWidgets.QGroupBox(DatasetPanel)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.addSortField = QtWidgets.QToolButton(self.groupBox)
        self.addSortField.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.addSortField.setObjectName("addSortField")
        self.horizontalLayout_2.addWidget(self.addSortField)
        self.removeSortField = QtWidgets.QToolButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeSortField.sizePolicy().hasHeightForWidth())
        self.removeSortField.setSizePolicy(sizePolicy)
        self.removeSortField.setObjectName("removeSortField")
        self.horizontalLayout_2.addWidget(self.removeSortField)
        self.moveSortField = QtWidgets.QToolButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveSortField.sizePolicy().hasHeightForWidth())
        self.moveSortField.setSizePolicy(sizePolicy)
        self.moveSortField.setObjectName("moveSortField")
        self.horizontalLayout_2.addWidget(self.moveSortField)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.sortByListWidget = QtWidgets.QListWidget(self.groupBox)
        self.sortByListWidget.setObjectName("sortByListWidget")
        self.verticalLayout_2.addWidget(self.sortByListWidget)
        self.sortAscendingCheckBox = QtWidgets.QCheckBox(self.groupBox)
        self.sortAscendingCheckBox.setChecked(True)
        self.sortAscendingCheckBox.setObjectName("sortAscendingCheckBox")
        self.verticalLayout_2.addWidget(self.sortAscendingCheckBox)
        self.limitCheckBox = QtWidgets.QGroupBox(self.groupBox)
        self.limitCheckBox.setCheckable(True)
        self.limitCheckBox.setChecked(False)
        self.limitCheckBox.setObjectName("limitCheckBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.limitCheckBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.limitSpinBox = QtWidgets.QSpinBox(self.limitCheckBox)
        self.limitSpinBox.setProperty("showGroupSeparator", True)
        self.limitSpinBox.setMaximum(999999)
        self.limitSpinBox.setSingleStep(100)
        self.limitSpinBox.setProperty("value", 20000)
        self.limitSpinBox.setObjectName("limitSpinBox")
        self.verticalLayout.addWidget(self.limitSpinBox)
        self.limRandomButton = QtWidgets.QRadioButton(self.limitCheckBox)
        self.limRandomButton.setChecked(True)
        self.limRandomButton.setObjectName("limRandomButton")
        self.verticalLayout.addWidget(self.limRandomButton)
        self.limTopButton = QtWidgets.QRadioButton(self.limitCheckBox)
        self.limTopButton.setObjectName("limTopButton")
        self.verticalLayout.addWidget(self.limTopButton)
        self.verticalLayout_2.addWidget(self.limitCheckBox)
        self.verticalLayout_3.addWidget(self.groupBox)

        self.retranslateUi(DatasetPanel)
        QtCore.QMetaObject.connectSlotsByName(DatasetPanel)

    def retranslateUi(self, DatasetPanel):
        _translate = QtCore.QCoreApplication.translate
        DatasetPanel.setWindowTitle(_translate("DatasetPanel", "Dataset Panel"))
        self.label.setText(_translate("DatasetPanel", "Histogram Color by:"))
        self.groupBox.setTitle(_translate("DatasetPanel", "Output"))
        self.label_2.setText(_translate("DatasetPanel", "Sort Output"))
        self.addSortField.setToolTip(_translate("DatasetPanel", "Add Field"))
        self.addSortField.setText(_translate("DatasetPanel", "+"))
        self.removeSortField.setToolTip(_translate("DatasetPanel", "Remove selected field"))
        self.removeSortField.setText(_translate("DatasetPanel", "-"))
        self.moveSortField.setToolTip(_translate("DatasetPanel", "Move selected field up"))
        self.moveSortField.setText(_translate("DatasetPanel", "^"))
        self.sortAscendingCheckBox.setText(_translate("DatasetPanel", "Ascending"))
        self.limitCheckBox.setTitle(_translate("DatasetPanel", "Limit Output"))
        self.limRandomButton.setText(_translate("DatasetPanel", "Random Subset"))
        self.limTopButton.setText(_translate("DatasetPanel", "Top"))

