# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlotDialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PlotDialog(object):
    def setupUi(self, PlotDialog):
        PlotDialog.setObjectName(_fromUtf8("PlotDialog"))
        PlotDialog.resize(334, 392)
        self.verticalLayout_2 = QtGui.QVBoxLayout(PlotDialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.description = QtGui.QLabel(PlotDialog)
        self.description.setWordWrap(True)
        self.description.setObjectName(_fromUtf8("description"))
        self.verticalLayout_2.addWidget(self.description)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(PlotDialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.xCombo = QtGui.QComboBox(PlotDialog)
        self.xCombo.setObjectName(_fromUtf8("xCombo"))
        self.horizontalLayout.addWidget(self.xCombo)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(PlotDialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.yCombo = QtGui.QComboBox(PlotDialog)
        self.yCombo.setObjectName(_fromUtf8("yCombo"))
        self.horizontalLayout_2.addWidget(self.yCombo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(PlotDialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.zCombo = QtGui.QComboBox(PlotDialog)
        self.zCombo.setObjectName(_fromUtf8("zCombo"))
        self.horizontalLayout_3.addWidget(self.zCombo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(PlotDialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.cCombo = QtGui.QComboBox(PlotDialog)
        self.cCombo.setObjectName(_fromUtf8("cCombo"))
        self.horizontalLayout_4.addWidget(self.cCombo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.logCheckBox = QtGui.QCheckBox(PlotDialog)
        self.logCheckBox.setObjectName(_fromUtf8("logCheckBox"))
        self.verticalLayout_2.addWidget(self.logCheckBox)
        self.frame = QtGui.QFrame(PlotDialog)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.minCheckBox = QtGui.QCheckBox(self.frame)
        self.minCheckBox.setObjectName(_fromUtf8("minCheckBox"))
        self.horizontalLayout_5.addWidget(self.minCheckBox)
        self.minSpinBox = QtGui.QDoubleSpinBox(self.frame)
        self.minSpinBox.setEnabled(False)
        self.minSpinBox.setObjectName(_fromUtf8("minSpinBox"))
        self.horizontalLayout_5.addWidget(self.minSpinBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.maxCheckBox = QtGui.QCheckBox(self.frame)
        self.maxCheckBox.setObjectName(_fromUtf8("maxCheckBox"))
        self.horizontalLayout_6.addWidget(self.maxCheckBox)
        self.maxSpinBox = QtGui.QDoubleSpinBox(self.frame)
        self.maxSpinBox.setEnabled(False)
        self.maxSpinBox.setObjectName(_fromUtf8("maxSpinBox"))
        self.horizontalLayout_6.addWidget(self.maxSpinBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.binCheckBox = QtGui.QCheckBox(self.frame)
        self.binCheckBox.setObjectName(_fromUtf8("binCheckBox"))
        self.horizontalLayout_7.addWidget(self.binCheckBox)
        self.binSpinBox = QtGui.QSpinBox(self.frame)
        self.binSpinBox.setEnabled(False)
        self.binSpinBox.setMinimum(1)
        self.binSpinBox.setProperty("value", 10)
        self.binSpinBox.setObjectName(_fromUtf8("binSpinBox"))
        self.horizontalLayout_7.addWidget(self.binSpinBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addWidget(self.frame)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.buttonBox = QtGui.QDialogButtonBox(PlotDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(PlotDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), PlotDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), PlotDialog.reject)
        QtCore.QObject.connect(self.maxCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.maxSpinBox.setEnabled)
        QtCore.QObject.connect(self.minCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.minSpinBox.setEnabled)
        QtCore.QObject.connect(self.binCheckBox, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.binSpinBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(PlotDialog)

    def retranslateUi(self, PlotDialog):
        PlotDialog.setWindowTitle(_translate("PlotDialog", "Scatter Plot", None))
        self.description.setText(_translate("PlotDialog", "TextLabel", None))
        self.label.setText(_translate("PlotDialog", "X Axis:", None))
        self.label_2.setText(_translate("PlotDialog", "Y Axis:", None))
        self.label_3.setText(_translate("PlotDialog", "Z Axis:", None))
        self.label_4.setText(_translate("PlotDialog", "Color By:", None))
        self.logCheckBox.setText(_translate("PlotDialog", "Log Scale (Colors)", None))
        self.minCheckBox.setText(_translate("PlotDialog", "Min:", None))
        self.maxCheckBox.setText(_translate("PlotDialog", "Max:", None))
        self.binCheckBox.setText(_translate("PlotDialog", "Bins:", None))

